apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-uuwl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-uuwl
    app.kubernetes.io/part-of: ci1t-43256-0033-app
  name: devfile-sample-uuwl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-uuwl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-uuwl
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0033-tenant/ci1t-43256-0033-app/devfile-sample-uuwl@sha256:bc3ec96a64ce2a41c155444cd559e1e5005864e5d23872ebd5dbc6c2455b46b4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
